---
# Let's create a random password for root and then update all systems specified to the random password

 - hosts: all
   gather_facts: false
   remote_user: kman
   sudo:  yes

   tasks:
   - name: Install EPEL
     command: rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
     ignore_errors: true
   - name:  Install PIP for easy python package management     
     yum: name=python-pip state=latest
   - name: Use PIP to install passlib     
     command: pip install passlib
     ignore_errors: true
   - name: Generate a Random Password, Salt it, then hash it
     command: python -c "from passlib.hash import sha512_crypt; from passlib.utils import generate_password as generate; print sha512_crypt.encrypt(generate(size=20))"
     register: passit
   - name: Update the root password with a random password
     action: user name=root password={{ passit.stdout }} group=root
