---
# Update the Root Password on all specified systems
- hosts: all
  gather_facts: false
  remote_user: kman
  sudo: yes
  tasks:
  - name: Change Root Password
    action: user name=root password="{{ new_password }}"

