---
# Figure out which root password is in use, and then update it to the correct one.

- name: Test possible passwords
  local_action: shell sshpass -p {{ item }} ssh {{ user }}@{{ inventory_hostname }} date
  register: pastpass
  ignore_errors: true
  with_items: 
    - "{{ password_01 }}"
    - "{{ password_02 }}"
    - "{{ password_03 }}"    
    - "{{ password_04 }}"

- set_fact: ansible_ssh_pass={{ item.item }}
  with_items: pastpass.results
  when: item.rc == 0

- name: Set the correct password and hide the password
  shell: python -c 'import crypt; print crypt.crypt("{{ password_update }}", "$1$SomeSalt$")'
  register: passit
  no_log: True

- name: Update the password of user root
  user: name=root password={{ passit.stdout }} group=root
